[package]
name = "redis-analyzer"
version = "0.1.1"
authors = ["FetLife <dev@fetlife.com>"]
edition = "2018"
repository = "https://github.com/fetlife/redis-analyzer"
license = "MIT"
description = "Analyzes keys in Redis to produce breakdown of the most frequent prefixes."

[dependencies]
clap = { version = "2.33", features = ["yaml"] }
frequency = "^1.0"
frequency-hashmap = "^1.1"
humantime = "^1.2"
indicatif = "~0.11.0"
num_cpus = "^1.10"
rayon = "^1.1"
regex = "^1.1"
redis = "~0.10.0"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
