[package]
name = "redis-analyzer"
version = "0.1.0"
authors = ["FetLife <dev@fetlife.com>"]
edition = "2018"

[dependencies]
clap = { version = "2.33", features = ["yaml"] }
frequency = "*"
frequency-hashmap = "*"
indicatif = "*"
regex = "*"
redis = "0.10.0"
